// Real coordinates of the edges of the background image
const TOP_LEFT = { lat: 55.4519667, lon: -5.720025 };
const BOTTOM_RIGHT = { lat: 55.4172861, lon: -5.656125 };
// Launch position (not exactly the center)
const CENTER = [55.43539, -5.68593];

const IMAGE_WIDTH  = 8192;
const IMAGE_HEIGHT = 7812;
// Max z index generated by VIPS using the command:
// vips dzsave map.jpg tile --layout google --suffix .jpg[Q=85] --tile-size 256
const MAX_VIPS_ZOOM = 5;

const latScale = IMAGE_HEIGHT / (BOTTOM_RIGHT.lat - TOP_LEFT.lat);
const lonScale = IMAGE_WIDTH  / (BOTTOM_RIGHT.lon - TOP_LEFT.lon);

// Higher Lat = pixels closer to top
function LLtoPx(lat, lon) {
    const y = latScale * (lat - TOP_LEFT.lat);
    const x = lonScale * (lon - TOP_LEFT.lon);
    return [-y, x];
}

const mapBounds = [
    [-IMAGE_HEIGHT, 0],
    [0, IMAGE_WIDTH]
];

const map = L.map('map', {
    crs: L.CRS.Simple,
    // Zoom 0 is VIPS z=5 (closest tile)
    // Zoom -MAX_VIPS_ZOOM is VIPS z=0 (furthest tile)
    minZoom: -MAX_VIPS_ZOOM,
    // Allow zoom further than closest VIPS tile
    maxZoom: 3,
    // Prevent from going outside the map
    maxBounds: mapBounds,
    maxBoundsViscosity: 1.0
});

map.setView(
    LLtoPx(CENTER[0], CENTER[1]),
    0 // Zoom level
);

map.whenReady(function () {
    map.setMinZoom(
        map.getBoundsZoom(mapBounds, true)
    );
});

L.tileLayer('./map/tile/{z}/{y}/{x}.jpg', {
    noWrap: true,
    minZoom: -MAX_VIPS_ZOOM,
    // Prevents requesting any tiles smaller than generated
    maxNativeZoom: 0,
    zoomOffset: MAX_VIPS_ZOOM,
    bounds: mapBounds,
    errorTileUrl: './map/blank.png'
}).addTo(map);

// Scale for reference
// TODO: Figure out how to make it work properly (it's close enough for now)
L.control.scale({imperial: false}).addTo(map);

// Trajectory marker
// =================

function getPixelDistance(pos1, pos2) {
    return Math.sqrt(
        Math.pow(pos1.lat - pos2[0], 2) + 
        Math.pow(pos1.lng - pos2[1], 2)
    );
}

const markers = {};
const trajectories = {};
const stageColors = [
    'white', // Booster
    'yellow', // Sustainer
    'red' // Payload
];

const MIN_DISTANCE_PX = 2;

// Start by loading points prior to browser start
let loadingPrevTrail = true;

function appendToTrail(stageId, lat, lon) {
    const currentPos = LLtoPx(lat, lon);

    if (!trajectories[stageId]) {
        // Initialize trail
        const polyline = L.polyline([currentPos], {
            color: stageColors[stageId] || "black",
            weight: 3,
            opacity: 0.5
        }).addTo(map);
        trajectories[stageId] = polyline;
    } else {
        const polyline = trajectories[stageId];
        const points = polyline.getLatLngs();
        const lastPoint = points[points.length - 1];

        // Only draw point if it moved significantly (> MIN_DISTANCE_PX)
        if (!lastPoint || getPixelDistance(lastPoint, currentPos) > MIN_DISTANCE_PX) {
            polyline.addLatLng(currentPos);
        }
    }
}

window.updateMapPosition = function(stageId, lat, lon) {
    if (loadingPrevTrail) return; // Do not load if still loading history
    if (lat == null || lon == null || Number.isNaN(lat) || Number.isNaN(lon)) return;

    const currentPos = LLtoPx(lat, lon);

    // Update Marker
    if (!markers[stageId]) {
        markers[stageId] = L.circleMarker(currentPos, {
            radius: 8,
            color: stageColors[stageId] || 'black',
            fillOpacity: 1
        }).addTo(map);
    } else {
        markers[stageId].setLatLng(currentPos);
    }

    // Append to Trail
    appendToTrail(stageId, lat, lon, false);
};

// Initial loading of recorded trail history
fetch('./telemetry_latest.json', { cache: "no-store" }) // Don't rely on cache
    .then(response => response.json())
    .then(data => {
        if (!data.stages) {
            console.warn("[Map] Bootstrap failed: No stage data found in JSON.");
            return;
        }

        data.stages.forEach((stage, index) => {
            
            // 1. Draw the historical trail
            if (stage.history) {
                stage.history.forEach(point => {
                    if (point.lat && point.lon) {
                        appendToTrail(index, point.lat, point.lon, true);
                    }
                });
            }

            // 2. Place the marker at the last known position
            if (stage.lat && stage.lon) {
                const currentPos = LLtoPx(stage.lat, stage.lon);
                if (!markers[index]) {
                    markers[index] = L.circleMarker(currentPos, {
                        radius: 8,
                        color: stageColors[index] || 'white',
                        fillOpacity: 1
                    }).addTo(map);
                } else {
                    markers[index].setLatLng(currentPos);
                }
            }
        });
        loadingPrevTrail = false;
    })
    .catch(err => {
        console.error("Error loading the trail history", err);
        loadingPrevTrail = false;
    });